version: "3"
services:
  web-scraper:
    build: .
    container_name: playwright-bot
    user: root
    env_file:
      - .env.docker
    volumes:
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped